server:
  port: 8002
spring:
  application:
    name: gateway-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  routes: #给服务配置路由
    user-service:
      path: /user/**
    goods-service:
      path: /goods/**