server:
  port: 8002

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user/**
        filters:
          - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}